"""
notifier.py
Sends email notification when the training document is ready.
Uses Azure Communication Services (ACS) Email.
"""

import os
import logging
from azure.communication.email import EmailClient

logger = logging.getLogger(__name__)

ACS_CONNECTION_STRING = os.environ.get("ACS_CONNECTION_STRING", "")
EMAIL_FROM            = os.environ.get("NOTIFICATION_EMAIL_FROM", "")
EMAIL_TO              = os.environ.get("NOTIFICATION_EMAIL_TO", "")


def send_completion_email(
    video_name: str,
    document_name: str,
    section_count: int,
    blob_url: str,
):
    """Send a notification email when the training document is ready."""
    if not ACS_CONNECTION_STRING or not EMAIL_FROM or not EMAIL_TO:
        logger.warning("Email notification skipped — ACS credentials not configured.")
        return

    subject = f"✅ Training Document Ready: {video_name}"

    html_body = f"""
    <html>
    <body style="font-family: Calibri, Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">

      <div style="background: #0071C5; padding: 20px 30px;">
        <h2 style="color: white; margin: 0;">Training Document Ready</h2>
      </div>

      <div style="padding: 30px; background: #f9f9f9;">
        <p>Your training document has been successfully generated.</p>

        <table style="width:100%; border-collapse:collapse; margin: 20px 0;">
          <tr>
            <td style="padding:8px; font-weight:bold; width:40%; color:#0071C5;">Video:</td>
            <td style="padding:8px;">{video_name}</td>
          </tr>
          <tr style="background:#fff;">
            <td style="padding:8px; font-weight:bold; color:#0071C5;">Document:</td>
            <td style="padding:8px;">{document_name}</td>
          </tr>
          <tr>
            <td style="padding:8px; font-weight:bold; color:#0071C5;">Sections:</td>
            <td style="padding:8px;">{section_count} sections</td>
          </tr>
        </table>

        <div style="text-align:center; margin: 30px 0;">
          <a href="{blob_url}"
             style="background:#0071C5; color:white; padding:12px 30px;
                    text-decoration:none; border-radius:4px; font-weight:bold;">
            Download Training Document
          </a>
        </div>

        <p style="font-size:12px; color:#888;">
          This document was automatically generated by the Training Document Pipeline.
        </p>
      </div>

    </body>
    </html>
    """

    plain_body = (
        f"Your training document is ready.\n\n"
        f"Video: {video_name}\n"
        f"Document: {document_name}\n"
        f"Sections: {section_count}\n\n"
        f"Download: {blob_url}"
    )

    try:
        client = EmailClient.from_connection_string(ACS_CONNECTION_STRING)
        message = {
            "senderAddress": EMAIL_FROM,
            "recipients": {
                "to": [{"address": EMAIL_TO}],
            },
            "content": {
                "subject": subject,
                "plainText": plain_body,
                "html": html_body,
            },
        }
        poller = client.begin_send(message)
        result = poller.result()
        logger.info(f"Notification email sent. MessageId={result.get('id', 'unknown')}")
    except Exception as e:
        logger.error(f"Failed to send notification email: {e}")


def send_failure_email(video_name: str, error_message: str):
    """Send a notification email when the pipeline fails."""
    if not ACS_CONNECTION_STRING or not EMAIL_FROM or not EMAIL_TO:
        return

    subject = f"❌ Training Document Pipeline Failed: {video_name}"
    plain_body = (
        f"The training document pipeline failed for: {video_name}\n\n"
        f"Error: {error_message}\n\n"
        f"Please check the Azure Function logs for details."
    )

    try:
        client = EmailClient.from_connection_string(ACS_CONNECTION_STRING)
        message = {
            "senderAddress": EMAIL_FROM,
            "recipients": {"to": [{"address": EMAIL_TO}]},
            "content": {
                "subject": subject,
                "plainText": plain_body,
                "html": f"<p>{plain_body.replace(chr(10), '<br>')}</p>",
            },
        }
        poller = client.begin_send(message)
        poller.result()
        logger.info("Failure notification email sent.")
    except Exception as e:
        logger.error(f"Failed to send failure email: {e}")
