name: Deploy Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_089438A97E3B4C53BEFF012D561A183A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BFB0AE5B14CC40FCB80A1340ED2014B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7463D4DFE3AB433CBB959337220A3558 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: training-doc-processor
          package: .
